version: 2.1
slug: soft_ether_vpn_server
name: SoftEther VPN Server
description: SoftEther VPN Server for Home Assistant
advanced: true
arch:
  - armhf
  - armv7
  - amd64
init: false # passt das?
host_network: true
stage: experimental
startup: once # passt das?
privileged: 
  - NET_ADMIN