name: SoftEther VPN Server
version: 0.3
slug: soft_ether_vpn_server
description: SoftEther VPN Server for Home Assistant
url: "https://github.com/ToichiKuroba/hassio-softether"
arch:
  - armhf
  - armv7
  - amd64

advanced: true
host_network: true
map:
  - config:rw
  - share:rw
options: 
  config_dir: /config/softether
privileged: 
  - NET_ADMIN
schema:
  config_dir: match(^\/(config|share))
stage: experimental
