name: SoftEther VPN Server
version: 0.2
slug: soft_ether_vpn_server
description: SoftEther VPN Server for Home Assistant
url: "https://github.com/ToichiKuroba/hassio-softether"
arch:
  - armhf
  - armv7
  - amd64

boot: manual

advanced: true
stage: experimental

host_network: true
privileged: 
  - NET_ADMIN
